2025-01-30 16:45:29,328 INFO    MainThread:278706 [wandb_setup.py:_flush():76] Current SDK version is 0.16.4
2025-01-30 16:45:29,329 INFO    MainThread:278706 [wandb_setup.py:_flush():76] Configure stats pid to 278706
2025-01-30 16:45:29,329 INFO    MainThread:278706 [wandb_setup.py:_flush():76] Loading settings from /home/rodolfo/.config/wandb/settings
2025-01-30 16:45:29,329 INFO    MainThread:278706 [wandb_setup.py:_flush():76] Loading settings from /home/rodolfo/Insync/rodolfopcruz2@gmail.com/Google Drive/Estudo/Udacity/Machine Learning DevOps Engineer - Nanodegree/Exercicios/Curso_3/Exercicios_cap_3/genre_classification/check_data/wandb/settings
2025-01-30 16:45:29,329 INFO    MainThread:278706 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'run_group': 'dev', 'project': 'exercise_14'}
2025-01-30 16:45:29,329 INFO    MainThread:278706 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2025-01-30 16:45:29,330 WARNING MainThread:278706 [wandb_setup.py:_flush():76] Could not save program above cwd: /home/rodolfo/anaconda3/envs/mlflow-60000e2b97642ccc38c7a9ee503977f0abd54819/bin/pytest
2025-01-30 16:45:29,330 INFO    MainThread:278706 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': None, 'program_abspath': '/home/rodolfo/anaconda3/envs/mlflow-60000e2b97642ccc38c7a9ee503977f0abd54819/bin/pytest', 'program': '/home/rodolfo/anaconda3/envs/mlflow-60000e2b97642ccc38c7a9ee503977f0abd54819/bin/pytest'}
2025-01-30 16:45:29,330 INFO    MainThread:278706 [wandb_init.py:_log_setup():526] Logging user logs to /home/rodolfo/Insync/rodolfopcruz2@gmail.com/Google Drive/Estudo/Udacity/Machine Learning DevOps Engineer - Nanodegree/Exercicios/Curso_3/Exercicios_cap_3/genre_classification/check_data/wandb/run-20250130_164529-5p6ayj5d/logs/debug.log
2025-01-30 16:45:29,330 INFO    MainThread:278706 [wandb_init.py:_log_setup():527] Logging internal logs to /home/rodolfo/Insync/rodolfopcruz2@gmail.com/Google Drive/Estudo/Udacity/Machine Learning DevOps Engineer - Nanodegree/Exercicios/Curso_3/Exercicios_cap_3/genre_classification/check_data/wandb/run-20250130_164529-5p6ayj5d/logs/debug-internal.log
2025-01-30 16:45:29,330 INFO    MainThread:278706 [wandb_init.py:init():566] calling init triggers
2025-01-30 16:45:29,330 INFO    MainThread:278706 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2025-01-30 16:45:29,331 INFO    MainThread:278706 [wandb_init.py:init():616] starting backend
2025-01-30 16:45:29,331 INFO    MainThread:278706 [wandb_init.py:init():620] setting up manager
2025-01-30 16:45:29,334 INFO    MainThread:278706 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-01-30 16:45:29,337 INFO    MainThread:278706 [wandb_init.py:init():628] backend started and connected
2025-01-30 16:45:29,342 INFO    MainThread:278706 [wandb_init.py:init():720] updated telemetry
2025-01-30 16:45:29,355 INFO    MainThread:278706 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2025-01-30 16:45:30,071 INFO    MainThread:278706 [wandb_run.py:_on_init():2262] communicating current version
2025-01-30 16:45:30,712 INFO    MainThread:278706 [wandb_run.py:_on_init():2271] got version response upgrade_message: "wandb version 0.19.5 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2025-01-30 16:45:30,712 INFO    MainThread:278706 [wandb_init.py:init():804] starting run threads in backend
2025-01-30 16:45:31,480 INFO    MainThread:278706 [wandb_run.py:_console_start():2241] atexit reg
2025-01-30 16:45:31,480 INFO    MainThread:278706 [wandb_run.py:_redirect():2096] redirect: wrap_raw
2025-01-30 16:45:31,480 INFO    MainThread:278706 [wandb_run.py:_redirect():2161] Wrapping output streams.
2025-01-30 16:45:31,480 INFO    MainThread:278706 [wandb_run.py:_redirect():2186] Redirects installed.
2025-01-30 16:45:31,481 INFO    MainThread:278706 [wandb_init.py:init():847] run started, returning control to user process
2025-01-30 16:45:48,349 WARNING MsgRouterThr:278706 [router.py:message_loop():77] message_loop has been closed
